### ISSUE TITLE
Weird behavior of volume slider when menu disappears while pulling

### ISSUE THREAD

**Issue by oceanofsolaris** [Tudmotu/gnome-shell-extension-bettervolume#3]
The volume slider provided by this very nice extension can behave somewhat strangely. Steps to reproduce (on Fedora 21 with Gnome 3.14):

1. When the scrollwheel is used while the mouse is over the volume icon, a nice menu with the current volume level appears (I guess this is the aim of this extension:)
2. By moving the mouse off the volume icon onto this menu and dragging the volume slider, the volume level can then be further finetuned.
3. If one now takes too long to ponder what to do next *without releasing the mouse button*, the menu disappears again.
4. Now release the mouse button 
5. Immediately move the mouse pointer over the volume icon to change volume again.
6. Effect: The volume is close to maximum, independently of where it was before.

Expected effect: Volume level stays where I willingly set it. Current effect can be painful with headphones.

Some speculation: The timeout to make the menu disappear does not stop while the mouse button is pressed. If the menu has disappeared, it does not get the mouse release event. It thus still sets the volume level according to the current x position of the mouse, which is far to the right while over the volume icon.

In this case, a fix could be:
a) stop the timeout while the mousebutton is pressed? or
b) 'release' the mouse button when the menu times out?

**Comment by Tudmotu** [comment]
Thank you for reporting :)

I'll go with you first suggestion (disable the timeout).
Will update on this ticket.

**Comment by Tudmotu** [comment]
@oceanofsolaris This fix was uploaded to extensions.gnome.org, so you can update your extension :)
I hope it does fix the issue for you. If not, please let me know.

**Comment by oceanofsolaris** [comment]
Works perfectly now. Thanks for the fast response and fix.

**Comment by Tudmotu** [comment]
Great! :)
Again, thank you for reporting this issue!
